name: Deploy to Hugging Face Spaces

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - name: Push vers Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "ci@example.com"
          git config --global user.name "GitHub Actions"
          git remote add hf https://aimethaer1:$HF_TOKEN@huggingface.co/spaces/aimethaer1/rattrapage-git-mbog
          git push hf HEAD:main --force
